### ISSUE TITLE
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorCopy.cpp:70

### ISSUE THREAD

**Issue by monk42** [sacmehta/ESPNetv2#4]
When I run the segmentation codes , i got this error!  
![59fdee984bae45d85735b2e52b0e8b5](https://user-images.githubusercontent.com/33028017/49715975-308dfc80-fc8d-11e8-8a30-61f31f4cda25.png)

It seems that there is a problem in calculating the loss function！The loss value cannot be calculated.

I run this codes in pytorch0.4.1 and python3 and opencv 3.2.0

**Comment by sacmehta** [comment]
Does your machine has GPU with CUDa?

**Comment by monk42** [comment]
yes,  it's cuda 8.0, cudnn5.1 and gpu is 1050ti!

**Comment by sacmehta** [comment]
You might want to upgrade it and try. I was using Cuda 9.0 and cudnn 7

**Comment by monk42** [comment]
OK   I will try i, thanks!

**Comment by monk42** [comment]
Thanks, I have solved this problem. It turned out that I didn't convert 255 of the input label to 19, not because of the problem of the CUDA version.
There are 255 label in the voc12 data set. How can I handle this data set to use your network properly?

**Comment by sacmehta** [comment]
You can ignore it in the loss function.

nn.CrossEntropy(ignore_index=255)

**Comment by monk42** [comment]
If I set nClasses = 21，is 255 label also ignored  in IOUEval.py ?

**Comment by sacmehta** [comment]
The easiest way is to do something like this:

https://github.com/sacmehta/ESPNetv2/blob/df58a62b32ae17074ab7a8610bd319365f7eb85f/segmentation/DataSet.py#L40

For cityscapes, I map 255 to 19. For VOC, you can map 255 to 0

**Comment by monk42** [comment]
I really appreciate your answer, it's help me a lot.  I'll try the approach you suggested. 
Thanks !

**Comment by monk42** [comment]
When you test ESPNetv2 on camvid dataset, did you augment the dataset and did you ignore the background classes when training ？

**Comment by sacmehta** [comment]
We didn’t train on CamVid dataset.

**Comment by monk42** [comment]
sorry，I was mistaken.
